### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'models'

### ISSUE THREAD

**Issue by weakish** [aoout/bilimusic#1]
After installing bilimusic via pip, running it triggered this error:

```
raceback (most recent call last):
  File "bin/bilimusic", line 8, in <module>
    sys.exit(run())
  File "lib/python3.10/site-packages/bilimusic/cli.py", line 18, in run
    shutil.copytree(Path('models'), models_path)
  File "lib/python3.10/shutil.py", line 554, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: 'models'
```

As a workaround, I manually downloaded the models from https://github.com/aoout/bilimusic/tree/master/models and put them under `~/.bilimusic/models/`.

**Comment by aoout** [comment]
I just updated the package on pypi to 0.1.1. How about now?

**Comment by weakish** [comment]
I installed bilimusic 0.1.1 on my machine and I can confirm that this issue has been resolved.

Thanks a lot!
